### ISSUE TITLE
Nice one!

### ISSUE THREAD

**Issue by FGRibreau** [tyler-johnson/couchdb-jwt-redis-store#1]
Nice one @tyler-johnson !

This library for couchdb-jwt will be shared in our next [RedisWeekly](http://redisweekly.com) tomorrow morning!

**Comment by tyler-johnson** [comment]
Awesome can't wait! This relies on a sister library [CouchDB JWT](http://ghub.io/couchdb-jwt) so I'll make sure to get the documentation out on that before tomorrow.

Thanks for the heads up!
